export { apiService } from './api';
export { customerService } from './customerService';
export type { Customer, CreateCustomerData } from './customerService';
export { productService } from './productService';
export type { Product, CreateProductData, UpdateProductData } from './productService';
export { inventoryService } from './inventoryService';
export type { Inventory, StockMovement } from './inventoryService';
export { orderService } from './orderService';
export type { Order, OrderItem, CreateOrderData } from './orderService';
export { authService } from './authService';
export type { LoginData, RegisterData } from './authService';
export type { ApiResponse } from './api';
export { dashboardService } from './dashboardService';
export { reportingService } from './reportingService';
export { customerActivityService } from './customerActivityService';
export type { CustomerActivity, CreateCustomerActivityData } from './customerActivityService';
